from django.conf.urls.defaults import *

urlpatterns = patterns('apps.tabletop.views', 
    url('^report/add/$','add_battle_report',
        name='url_add_battle_report'),
    #url('^new/report/add/$','add_new_battle_report',
    #    name='url_add_new_battle_report'),
    url('^reports/$','index',
        name='battle_report_index'),
    url('^reports/show/(?P<id>\d+)/$','show_battle_report',
        name='show_battle_report'),
    url('^reports/(?P<id>\d+)/$', 'show_battle_report',
        name='url_battle_report'),
    url('^reports/delete/(?P<id>\d+)/(?P<approve>(approve|force))/$','delete_battle_report',
        name='url_delete_battle_report'),
    url('^reports/(?P<id>\d+)/edit/$','add_battle_report',{'action':'edit'},
        name='url_edit_battle_report'),
    url('^rosters/search/$','search_rosters',
        name='url_search_rosters'),
    url('^rosters/all/$','index_rosters',
        name='url_all_rosters'),
    url('^rosters/pts/(?P<pts>\d+)/$','user_rosters',
        name='url_pts_rosters'),
    url('^rosters/complex/(?P<race>[\w\s-]+)/(?P<pts>\d+)/$','user_rosters',
        name='url_complex_rosters'),
    url('^rosters/complex/(?P<race>[\w\s-]+)/$','user_rosters',
        name='url_complex_rosters'),
    url('^rosters/race/(?P<race>[\w\s-]+)/$','user_rosters',
        name='url_race_rosters'),
    url('^rosters/(?P<nickname>[\w\s-]+)/$','user_rosters',
        name='url_user_rosters'),
    url('^rosters/(?P<nickname>[\w\s-]+)/(?P<race>[\w\s-]+)/$','user_rosters',
        name='url_user_rosters'),
    url('^rosters/(?P<nickname>[\w\s-]+)/(?P<race>[\w\s-]+)/(?P<pts>\d+)/$','user_rosters',
        name='url_user_rosters'),
    url('^rosters/$','user_rosters',
        name='url_user_rosters'),
    url('^roster/add/$','action_roster',
        name='url_add_roster'),
    url('^roster/spawn/(?P<id>\d+)/$', 'action_roster',{'action': 'spawn'},
        name='url_spawn_roster'),
    url('^roster/edit/(?P<id>\d+)/$', 'action_roster',{'action': 'edit'},
        name='url_edit_roster'),
    url('^roster/delete/(?P<id>\d+)/(?P<action>(approve|purge))/$', 'delete_roster',{'action': ''},
        name='url_delete_roster'),
    url('^roster/show/(?P<id>\d+)/$','show_roster',
        name='url_show_roster'),
    url('^roster/unorphan/(?P<id>\d+)/$','unorphan',
        name='url_unorphan_roster'),
    url('^sphinx/rosters/$', 'sphinx_search_rosters',
        name='url_sph_search_rosters'),
    #xhr
    url('^xhr/rosters/$','xhr_rosters', {'search': 'test'}, name='xhr_search_rosters'),
    url('^xhr/rosters/(?P<search>[\w\s_]+)/$','xhr_rosters', name='xhr_search_rosters'),
    url('^xhr/get/roster/(?P<id>\d+)/$', 'xhr_get_roster', name='xhr_get_roster'),
)

