from django.conf.urls import patterns, include, url
from apps.core.shortcuts import direct_to_template
from django.contrib.auth.decorators import login_required
from apps.accounts import views


urlpatterns = patterns(
    'apps.accounts.views',
    url(r'^login/$', views.LoginView.as_view(), name='login'),
    url(r'^logout/$', views.LogoutView.as_view(), name='logout'),
    url(r'^profile/$',
        login_required(views.ProfileSelfView.as_view()), name='profile'),
    url(r'^profiles/(?P<pk>\d+)/$',
        login_required(views.ProfileView.as_view()),
        name='profile'),
    url(r'^profiles/(?P<slug>[\w\d\-_ \.]+)/$',
        login_required(views.ProfileView.as_view()), name='profile-by-nick'),

    url(r'^accounts/password/(?P<sid>[\w\d]+)/restore/$',
        views.PasswordRestoreView.as_view(),
        name='password-restore'),
    url(r'^accounts/password/restore/initiate/$',
        views.PasswordRestoreInitiateView.as_view(),
        name='password-restore-initiate'),
    url(r'^accounts/password/change/$',
        login_required(views.PasswordChangeView.as_view()),
        name='password-change',),
    url(r'^accounts/users/$', login_required(views.UserListView.as_view()),
        name='users'),
    url(r'^register/$', views.RegisterView.as_view(), name='register'),
    url(r'^profile/update/$', views.ProfileUpdateView.as_view(),
        name='profile-update'),
    url(r'^profile/pm/inbox/$',
        login_required(views.PMInboxListView.as_view()),
        name='pm-inbox'),
    url(r'^profile/pm/outbox/$',
        login_required(views.PMOutboxListView.as_view()),
        name='pm-outbox'),
    url(r'^profile/pm/(?P<pk>\d+)/$',
        login_required(views.PMDetailView.as_view()),
        name='pm-detail'),
    url(r'^profile/pm/(?P<pk>\d+)/reply/$',
        login_required(views.PMReplyView.as_view()), name='pm-reply'),
    url(r'^profile/pm/send/$',
        login_required(views.PMSendView.as_view()), name='pm-create'),

    url(r'^accounts/(?P<pk>\d+)/warnings/$',
        login_required(views.PolicyWarningListView.as_view()),
        name='warning-list'),
    url(r'^accounts/warnings/$',
        login_required(views.PolicyWarningListView.as_view()),
        name='warning-list'),
    url(r'^accounts/warnings/(?P<pk>\d+)/$',
        login_required(views.PolicyWarningDetailView.as_view()),
        name='warning-detail'),
    url(r'^accounts/(?P<pk>\d+)/warnings/create/$',
        login_required(views.PolicyWarningCreateView.as_view()),
        name='warning-create'),
    url(r'^accounts/warnings/(?P<pk>\d+)/update/$',
        login_required(views.PolicyWarningUpdateView.as_view()),
        name='warning-update'),
    url(r'^accounts/warnings/(?P<pk>\d+)/delete/$',
        login_required(views.PolicyWarningDeleteView.as_view()),
        name='warning-delete'),

    url(r'^register/success/$', direct_to_template,
        {'template': 'accounts/register_success.html'},
        name='register-success'),
    url(r'^accounts/banned/$', direct_to_template,
        {'template': 'accounts/banned.html'}, name='banned'),
    url(r'password/changed/$', direct_to_template,
        {'template': 'accounts/password_changed.html'},
        name='password-changed'),
    url(r'^accounts/read/only/$', direct_to_template,
        {'template': 'accounts/read_only.html'}, name='read-only'),
)
