# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ranks',
            field=models.ManyToManyField(blank=True, to='wh.Rank'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uin',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='uin (icq number)'),
        ),
    ]
