# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 02:49
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('editor', models.CharField(blank=True, max_length=255, verbose_name='editor')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='original URL')),
                ('content', models.TextField(verbose_name='content')),
                ('cache_content', models.TextField(blank=True, null=True, verbose_name='cache content')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='dateTime')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('author_ip', models.CharField(blank=True, max_length=16, verbose_name='author ip address')),
                ('is_event', models.BooleanField(default=False, verbose_name='is event')),
                ('syntax', models.CharField(blank=True, choices=[('textile', 'textile'), ('bb-code', 'bb-code')], max_length=20, null=True, verbose_name='Syntax')),
                ('reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='reason')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejeceted'), ('queued', 'queued'), ('revision', 'revision')], default='queued', max_length=32)),
                ('resend', models.BooleanField(default=False, help_text='marks if news notification should resend', verbose_name='resend')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Attachment')),
            ],
            options={
                'verbose_name_plural': 'Archived News',
                'ordering': ['-id'],
                'permissions': (('edit_archived_news', 'Can edit archived news'),),
                'verbose_name': 'Archived Article',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'verbose_name': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='event title', max_length=256, verbose_name='title')),
                ('content', models.TextField(help_text='content event text, description, further manual and so on', verbose_name='content')),
                ('content_html', models.TextField(blank=True, help_text='rendered html content', null=True, verbose_name='content html')),
                ('date_start', models.DateTimeField(help_text='when event date starts', verbose_name='date start')),
                ('date_end', models.DateTimeField(blank=True, help_text='when event date ends', null=True, verbose_name='date end')),
                ('type', models.CharField(choices=[('game', 'Game'), ('tournament', 'Tournament'), ('order', 'Order'), ('pre-release', 'Pre-release'), ('release', 'Release'), ('festivity', 'Festivity')], default='game', max_length=16, verbose_name='type')),
                ('league', models.CharField(blank=True, choices=[('wh40k', 'Warhammer 40000'), ('whfb', 'Warhammer fantasy battle'), ('mtg', 'Magic the gathering'), ('board', 'Board gaming'), ('dnd', 'Dungeons and Dragons')], default='wh40k', help_text='game league', max_length=32, null=True, verbose_name='league')),
                ('is_finished', models.BooleanField(default=False, verbose_name='is finished')),
                ('is_all_day', models.BooleanField(default=False, help_text='marks if event could place whole day', verbose_name='is all day')),
                ('participants', models.ManyToManyField(blank=True, help_text='participants would take a part in the event', related_name='event_users_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Events',
                'ordering': ['is_finished', 'date_start'],
                'verbose_name': 'Event',
            },
        ),
        migrations.CreateModel(
            name='EventPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='event place title', max_length=512, verbose_name='title')),
                ('address', models.CharField(blank=True, help_text='event place address', max_length=1024, null=True, verbose_name='address')),
                ('contacts', models.CharField(blank=True, help_text='contacts/help who to find it', max_length=256, null=True, verbose_name='contacts')),
            ],
            options={
                'verbose_name_plural': 'Event Places',
                'verbose_name': 'Event Place',
            },
        ),
        migrations.CreateModel(
            name='EventWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, verbose_name='created on')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_watch_set', to='news.Event', verbose_name='event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_watch_user_set', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name_plural': 'Event watches',
                'verbose_name': 'Event watch',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('author', models.CharField(max_length=255, verbose_name='author')),
                ('editor', models.CharField(blank=True, max_length=255, verbose_name='editor')),
                ('url', models.CharField(blank=True, max_length=200, verbose_name='original URL')),
                ('content', models.TextField(verbose_name='content')),
                ('cache_content', models.TextField(blank=True, null=True, verbose_name='cache content')),
                ('date', models.DateTimeField(default=datetime.datetime.now, verbose_name='dateTime')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('author_ip', models.CharField(blank=True, max_length=16, verbose_name='author ip address')),
                ('is_event', models.BooleanField(default=False, verbose_name='is event')),
                ('syntax', models.CharField(blank=True, choices=[('textile', 'textile'), ('bb-code', 'bb-code')], max_length=20, null=True, verbose_name='Syntax')),
                ('reason', models.CharField(blank=True, max_length=1024, null=True, verbose_name='reason')),
                ('status', models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejeceted'), ('queued', 'queued'), ('revision', 'revision')], default='queued', max_length=32)),
                ('resend', models.BooleanField(default=False, help_text='marks if news notification should resend', verbose_name='resend')),
                ('attachment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.Attachment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category')),
                ('owner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name_plural': 'News',
                'permissions': (('edit_news', 'Can edit news'), ('del_restore_comments', 'Can delete and restore comments'), ('edit_comments', 'Can edit comments'), ('purge_comments', 'Can purge comments')),
                'verbose_name': 'Article',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=datetime.datetime.now, help_text='date time when instance was created', verbose_name='created on')),
                ('expired_on', models.DateTimeField(help_text='date when note is expired', verbose_name='expired on')),
                ('content', models.TextField(help_text='content', verbose_name='content')),
                ('for_authenticated_only', models.BooleanField(default=False, help_text='for authenticated users only', verbose_name='for authenticated only')),
                ('sign', models.BooleanField(help_text='if the purity seal should be with its note', verbose_name='sign')),
                ('type', models.CharField(choices=[('success', 'success'), ('info', 'info'), ('alert', 'alert'), ('warning', 'warning'), ('default', 'default')], default='success', max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='place',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_place_set', to='news.EventPlace', verbose_name='event place'),
        ),
        migrations.AddField(
            model_name='archivednews',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Category'),
        ),
        migrations.AddField(
            model_name='archivednews',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='archivednews', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AlterUniqueTogether(
            name='eventwatch',
            unique_together=set([('event', 'user')]),
        ),
    ]
