# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-05 02:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='participants would take a part in the event', related_name='event_users_sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
