# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 21:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pybb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='moderators',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Moderators'),
        ),
        migrations.AlterField(
            model_name='forum',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='private participants list', related_name='forum_user_sets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='forum',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='poll_set', to='pybb.Topic'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user_ip',
            field=models.GenericIPAddressField(default='127.0.0.1', verbose_name='User IP'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='updated',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Updated'),
        ),
    ]
