from django.conf.urls import *

urlpatterns = patterns('apps.tabletop.views',
    url('^report/add/$', 'add_battle_report',
        name='battle-report-add'),
    #url('^new/report/add/$', 'add_new_battle_report',
    #    name='url_add_new_battle_report'),
    #url('^reports/$', 'index',
    #    name='battle-reports'), #battle_report_index ? <-- stale url schema
    url('^reports/$', 'reports',
        name='battle-reports'),
    url('^reports/show/(?P<id>\d+)/$', 'show_battle_report',
        name='battle-report'),
    url('^reports/(?P<id>\d+)/$', 'show_battle_report',
        name='battle-report'),
    url('^reports/delete/(?P<id>\d+)/(?P<approve>(approve|force))/$', 'delete_battle_report',
        name='battle-report-delete'),
    url('^reports/(?P<id>\d+)/edit/$', 'add_battle_report',{'action':'edit'},
        name='battle-report-edit'),
    url('^rosters/search/$', 'search_rosters',
        name='rosters-search'),
    url('^rosters/all/$', 'index_rosters',
        name='rosters-index'),
    url('^rosters/pts/(?P<pts>\d+)/$', 'user_rosters',
        name='rosters-pts'),
    #url('^rosters/complex/(?P<race>[\w\s-]+)/(?P<pts>\d+)/$', 'user_rosters',
    #    name='url_complex_rosters'),
    #url('^rosters/complex/(?P<race>[\w\s-]+)/$', 'user_rosters',
    #    name='url_complex_rosters'),
    #deprecated, cleanse
    #url('^rosters/race/(?P<race>[\w\s-]+)/$', 'user_rosters',
    #    name='url_race_rosters'),
    url('^rosers/codex/(?P<id>\d+)/(?P<revision>\d+)/$', 'codex_rosters',
        name='rosters-codex'),
    url('^rosters/(?P<nickname>[\w\s-]+)/$', 'user_rosters',
        name='rosters'),
    #url('^rosters/(?P<nickname>[\w\s-]+)/(?P<race>[\w\s-]+)/$', 'user_rosters',
    #    name='url_user_rosters'),
    #url('^rosters/(?P<nickname>[\w\s-]+)/(?P<race>[\w\s-]+)/(?P<pts>\d+)/$', 'user_rosters',
    #    name='url_user_rosters'),
    url('^rosters/$', 'user_rosters',
        name='rosters'),
    url('^roster/add/$', 'action_roster',
        name='roster-add'),
    url('^roster/spawn/(?P<id>\d+)/$', 'action_roster',{'action': 'spawn'},
        name='roster-spawn'),
    url('^roster/edit/(?P<id>\d+)/$', 'action_roster',{'action': 'edit'},
        name='roster-edit'),
    url('^roster/delete/(?P<id>\d+)/(?P<action>(approve|purge))/$', 'delete_roster', {'action': ''},
        name='roster-delete'),
    url('^roster/show/(?P<id>\d+)/$', 'show_roster',
        name='roster'),
    url('^roster/unorphan/(?P<id>\d+)/$', 'unorphan',
        name='roster-unorphan'),
    url('^sphinx/rosters/$', 'sphinx_search_rosters',
        name='roster-sph'),
    #codexes
    url('^codex/add/$', 'action_codex',
        name='codex-add'),
    url('^codex/edit/(?P<id>\d+)/$', 'action_codex',
        {'action': 'edit'},
        name='codex-edit'),
    url('^codex/(?P<id>\d+)/$', 'show_codex',
        name='codex'),
    url('^codexes/$', 'show_codexes',
        name='codexes'),
)

