from django.conf.urls.defaults import *
from apps.core.shortcuts import direct_to_template
from django.utils.translation import ugettext_lazy as _

urlpatterns = patterns('apps.wh.views',
    #(r'^$', direct_to_template,
    #    {'template':'homepage.html'}),
    (r'^login/$', 'login'),
    url('^sulogin/$', 'sulogin',
        name='url_superlogin'),
    url('^accounts/login/$', 'login',name='auth_login'),
    url('^logout/$', 'logout',name='auth_logout'),
    url('^accounts/password/change/$', 'change_password',name='auth_password_change'), 
        (r'^password/recover/$', 'password_recover'),
    url(r'^accounts/profile/$', 'profile', name='url_profile'),
    url('^accounts/profile/real/(?P<account_name>[\w\s-]+)/$', 'profile',
        name='url_real_profile'),
    url('^accounts/profile/(?P<nickname>[\w\s-]+)/$', 'profile_by_nick',
        name='profile_by_nick'),
    (r'^accounts/$', 'users'),
    url('^accounts/get/users/$','x_get_users_list',
        name='url_x_get_users_list_null'),
    url('^accounts/get/users/(?P<nick_part>[\w\s-]+)/$','x_get_users_list',
        name='url_x_get_users_list'),
    (r'^accounts/old_update/profile/$', 'update_profile_old'),
    (r'^accounts/update/profile/successfull/$', direct_to_template,
        {'template': 'accounts/updated.html'}),
    url(r'^accounts/update/profile/$', 'update_profile',
        name='url_update_profile'),
    url('^accounts/get/avatar/(?P<nickname>[\w\s-]+)/$', 'get_user_avatar',
        name='url_get_avatar'),
    url('^accounts/get/photo/(?P<nickname>[\w\s-]+)/$', 'get_user_photo',
        name='url_user_photo'),
    url('^get/race/icon/(?P<race>[\w\s-]+)/$','get_race_icon',
        name='url_get_race_icon'),
    (r'^accounts/get/side/icon/(?P<nickname>[\w\s-]+)/$','get_user_side_icon'),
    #deprecated use xhr instead of this, todo: cleanse
    (r'^accounts/get/armies/(?P<id>\d+)/$', 'get_armies_raw'),
    url(r'^xhr/get/armies/$', 'xhr_get_armies',
        name='xhr_get_armies'),
    url(r'^xhr/get/armies/(?P<id>\d+)/$', 'xhr_get_armies',
        name='xhr_get_armies'),
    (r'^accounts/get/skins/(?P<id>\d+)/$', 'get_skins_raw'),
    (r'^test/upload_avatar/$', 'upload_avatar'),
    (r'^test/armies_list/$', 'armies_list'),
    (r'^test/profile/$', direct_to_template,
        {'template':'accounts/test.html'}),
    (r'^pm/$','pm_view'),
    url('^pm/send/user/(?P<nickname>[\w\s-]+)/$', 'send_pm',
        name='url_send_pm_by_nick'),
    url('^pm/send/$', 'send_pm',
        name='url_send_pm'),
    (r'^pm/sent/$', 'view_pms', {'outcome': True}),
    (r'^pm/income/$','view_pms'),
    (r'^pm/(?P<pm_id>\d+)/$', 'view_pm'),
    (r'^pm/(?P<pm_id>\d+)/delete/(?P<approve>(approve|force))/$', 'delete_pm'),
    (r'^pm/(?P<pm_id>\d+)/delete/$', 'delete_pm'),
    (r'^test/send_pm/$', 'send_pm'),
    (r'^test/view_pm/$', 'view_pm'),
    #(r'^test/ajax_test/$', 'ajax_test'),
    url(r'^register/$', 'onsite_register',name='registration_register'),
    (r'^register/get_math_image/$', 'get_math_image'), #for joke sake
    (r'^register/get_math_image/(?P<sid>\w+)/$','get_math_image'),
    (r'^feedback/wishes/$', 'view_wish_list'),
    (r'^feedback/wishes/add/$', 'add_wish'),
    (r'^feedback/wishes/(?P<wish_id>\d+)/(?P<filter>(approve|publish|unapprove|unpublish|done))/$', 'manage_wish'), 
    (r'^ranks/(?P<id>\d+)/$', 'show_rank'),
    url('^ranks/(?P<codename>[\w\s]+)/$', 'show_rank',
        name='url_show_rank'),
    (r'^ranks/(?P<codename>[\w\s]+)/update/$', 'edit_rank'),
    (r'^ranks/(?P<codename>[\w\s]+)/get/$', 'get_rank'),
    (r'^ranks/(?P<codename>[\w\s]+)/get/formatted/$', 'get_rank', {'raw':False}),
    url('^warnings/(?P<nickname>[\w\s]+)/(?P<type>(increase|decrease))/$', 'alter_warning',
        name='alter_warning'),
    url('^warnings/alter/(?P<nickname>[\w\s]+)/$', 'alter_warning_form',
        name='alter_warning_form'),
    (r'^miniquote/get/raw', 'get_miniquote_raw'),
    (r'^favicon.ico$', 'favicon'),
    url(r'^l4d2/banner', direct_to_template, {'template': 'non40k/l4d2_banner.html'},
        name='url_nonwh_l4d2_banner'),
    #(r'^test/view_pm/(?P<page>\d+)/$', 'view_pm'),
    #(r'^test/urls_parse/$', 'urls_parse'),
)

